runtime: python27
api_version: 1
threadsafe: true
service: default

# instances and scaling
instance_class: F1
automatic_scaling:
  #max_idle_instances: automatic  # default value
  max_idle_instances: 1
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: markupsafe
  version: latest

inbound_services:
- warmup

handlers:
  # profiler
- url: /gae_mini_profiler/static
  static_dir: atuin/gae_mini_profiler/static
  secure: always
- url: /gae_mini_profiler/.*
  script: atuin.gae_mini_profiler.main.application
  secure: always

- url: /((android|apple|browser|favicon|manifest|mstile|safari){1}.*\.(png|ico|svg|json|xml))$
  static_files: static/min/img/favicon/\1
  upload: static/min/img/favicon/.*\.(png|ico|svg|json|xml)$
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: .*
  script: app.app
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*~
- ^(.*/)?Icon\r
- ^static/src
- ^.*\.po[t]
- ^.*\.md
- ^.*\.yaml
- ^.*requirements\.txt
